version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: platematch-backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: platematch-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge