apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: platematch-frontend
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/ingress: all
    spec:
      containers:
      - image: gcr.io/platematch/frontend
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_BACKEND_URL
          value: "https://api.a51m.xyz"
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"