apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: platematch-frontend
spec:
  template:
    spec:
      containers:
      - image: gcr.io/platematch/frontend
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_BACKEND_URL
          value: "https://platematch-backend-403018061895.europe-west1.run.app"  # Replace with actual backend URL after deployment
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"