name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: platematch

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      # Build and push backend Docker image
      - name: Build and push backend Docker image
        run: |
          IMAGE_NAME=gcr.io/platematch/backend
          docker build -t $IMAGE_NAME -f backend/Dockerfile backend/
          docker push $IMAGE_NAME

      # Build and push frontend Docker image
      - name: Build and push frontend Docker image
        run: |
          BACKEND_URL=$(gcloud run services describe platematch-backend --region=europe-west1 --format='value(status.url)')
          echo "Building frontend with BACKEND_URL: $BACKEND_URL"
          IMAGE_NAME=gcr.io/platematch/frontend
          docker build \
            --build-arg NEXT_PUBLIC_BACKEND_URL=$BACKEND_URL \
            -t $IMAGE_NAME \
            -f frontend/Dockerfile frontend/
          docker push $IMAGE_NAME

      # Deploy backend using service configuration
      - name: Deploy backend to Cloud Run
        run: |
          # Deploy backend first to get its URL
          BACKEND_URL=$(gcloud run services replace deployment/platematch-backend.yaml --region=europe-west1 --format='value(status.url)')
          echo "Backend URL: $BACKEND_URL"

      # Update frontend configuration with backend URL
      - name: Update frontend configuration
        run: |
          # Get backend URL from deployed service
          BACKEND_URL=$(gcloud run services describe platematch-backend --region=europe-west1 --format='value(status.url)')
          echo "Setting frontend to use backend URL: $BACKEND_URL"
          # Update frontend service configuration
          sed -i "s#value: \"https://.*\"#value: \"$BACKEND_URL\"#" deployment/platematch-frontend.yaml

      # Deploy frontend using service configuration
      - name: Deploy frontend to Cloud Run
        run: |
          FRONTEND_URL=$(gcloud run services replace deployment/platematch-frontend.yaml --region=europe-west1 --format='value(status.url)')
          echo "Frontend URL: $FRONTEND_URL"

      # Update backend CORS configuration
      - name: Update backend configuration
        run: |
          # Get actual frontend URL from service
          FRONTEND_URL=$(gcloud run services describe platematch-frontend --region=europe-west1 --format='value(status.url)')
          # Update backend CORS configuration
          sed -i "s#value: \"CORS_ORIGINS=.*\"#value: \"CORS_ORIGINS=$FRONTEND_URL\"#" deployment/platematch-backend.yaml
          # Redeploy backend with updated CORS
          gcloud run services replace deployment/platematch-backend.yaml --region=europe-west1

      # Set IAM policies for public access
      - name: Configure public access
        run: |
          gcloud run services set-iam-policy platematch-backend deployment/policy.yaml --region=europe-west1
          gcloud run services set-iam-policy platematch-frontend deployment/policy.yaml --region=europe-west1

      # Add environment verification step
      - name: Verify Service Configuration
        run: |
          echo "Backend Configuration:"
          gcloud run services describe platematch-backend --region=europe-west1 --format='yaml(spec.template.spec.containers[0].env)'
          
          echo "\nFrontend Configuration:"
          gcloud run services describe platematch-frontend --region=europe-west1 --format='yaml(spec.template.spec.containers[0].env)'
