name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master  # This will trigger the workflow on the 'master' branch

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: platematch

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      # Build and push backend Docker image
      - name: Build and push backend Docker image
        run: |
          IMAGE_NAME=gcr.io/platematch/backend
          docker build -t $IMAGE_NAME -f backend/Dockerfile backend/
          docker push $IMAGE_NAME

      # Build and push frontend Docker image
      - name: Build and push frontend Docker image
        run: |
          IMAGE_NAME=gcr.io/platematch/frontend
          docker build -t $IMAGE_NAME -f frontend/Dockerfile frontend/
          docker push $IMAGE_NAME

      # Deploy backend to Cloud Run
      - name: Deploy backend to Cloud Run
        run: |
          gcloud run deploy backend-service \
            --image gcr.io/platematch/backend \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated

      # Deploy frontend to Cloud Run
      - name: Deploy frontend to Cloud Run
        run: |
          gcloud run deploy frontend-service \
            --image gcr.io/platematch/frontend \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated
